import React from 'react';
import { FanNoiseCalc } from '@/components/calculators/FanNoiseCalc';

export const metadata = {
  title: 'Fan Noise Power Generation Calculator | MEPKit',
  description: 'Calculate the generated sound power level of fans based on motor power, volume capacity, and static pressure.',
};

export default function FanNoisePage() {
  return (
    <div className="container py-10 px-4">
      <h1 className="text-4xl font-bold mb-4 text-center">Fan Noise Power Generation</h1>
      <p className="text-lg text-muted-foreground mb-12 text-center max-w-3xl mx-auto">
        Estimate the overall sound power level ($L_N$) generated by a fan using empirical formulas, and analyze the noise distribution across standard octave bands based on the fan type.
      </p>
      
      <FanNoiseCalc />
    </div>
  );
}
